name: Check

on:
  pull_request:
    branches: [ 'master', 'release/v*' ]
  push:
    branches: [ 'master', 'release/v*' ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
        java: ['8', '11', '17', '21', '23']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - run: pip install "setuptools < 72"

      - name: Run Test
        run: python setup.py test

  test-free-threaded:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: ['8', '11', '17', '21', '23']
    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: ${{ matrix.java }}

        - uses: astral-sh/setup-uv@v3
        - run: |
            uv python install 3.13t
            uv venv --python 3.13t
            source .venv/bin/activate
            uv pip install pip
            echo PATH=$PATH >> $GITHUB_ENV

        - run: pip install "setuptools < 72"

        - name: Run Free-threaded Test
          run: python setup.py test

